name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          python3-pip autoconf libtool \
          pkg-config zlib1g-dev libncurses5-dev \
          libtinfo6 cmake libffi-dev libssl-dev

    - name: Initialize Buildozer
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
          echo -e "\n[app]\nsource.dir = .\nsource.main = main.py\nandroid.archs = arm64-v8a\n" > buildozer.spec
        else
          # 确保必要参数存在
          grep -q "source.dir" buildozer.spec || echo "source.dir = ." >> buildozer.spec
          grep -q "source.main" buildozer.spec || echo "source.main = main.py" >> buildozer.spec
        fi
        
        buildozer check

    - name: Install Buildozer
      run: |
        pip install buildozer cython==0.29.33

    - name: Build APK
      run: |
        buildozer -v android clean
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
        if-no-files-found: error
